# Generated by Django 3.1.5 on 2021-01-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='stand',
            new_name='name',
        ),
    ]
