# Generated by Django 3.1.5 on 2021-02-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20210201_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
