# Generated by Django 3.1.5 on 2021-02-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tour_friendly_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadium',
            old_name='friendly_name',
            new_name='full_name',
        ),
    ]
