# Generated by Django 3.1.5 on 2021-02-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20210202_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.match'),
        ),
    ]
