# Generated by Django 3.1.5 on 2021-02-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_ticket_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametype',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='gametype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.gametype'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.stadium'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.match'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.stadium'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
